name: Auto-deploy repo to S3 bucket

on:
  push:
    branches:
        - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Domain
        id: set_domain
        run: |
          DEPLOY_DOMAIN="central-asia.awscommunity.day"
          [[ $GITHUB_REF == "refs/heads/main" ]] || { echo "Invalid branch for deployment"; exit 1; }
          echo "DEPLOY_DOMAIN=$DEPLOY_DOMAIN" >> $GITHUB_ENV

      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_EC2_METADATA_DISABLED: true
        run: |
          aws s3 sync . s3://${{ env.DEPLOY_DOMAIN }} \
            --exclude ".git*"